### ISSUE TITLE
How to install on centos7

### ISSUE THREAD

**Issue by baigod** [eryx/hcaptcha#1]
How to install on centos7

When my console executes “make”, it says the following is wrong ：“

> cd src && make all
> make[1]: 进入目录“/root/hcaptcha/src”
> MAKE hiredis
> cd ../deps/hiredis && make 
> make[2]: 进入目录“/root/hcaptcha/deps/hiredis”
> make[2]: “sds.o”是最新的。
> make[2]: 离开目录“/root/hcaptcha/deps/hiredis”
>     LINK hcaptchad
> /usr/bin/ld: hcaptchad.o: undefined reference to symbol 'floor@@GLIBC_2.2.5'
> /usr/lib64/libm.so.6: error adding symbols: DSO missing from command line
> collect2: 错误：ld 返回 1
> make[1]: *** [hcaptchad] 错误 1
> make[1]: 离开目录“/root/hcaptcha/src”
> make: *** [all] 错误 2

**Comment by eryx** [comment]
@15174834  fixed gcc link error on CentOS 7.x, please update your local sourc code (git pul origin master) and re-make again.
https://github.com/eryx/hcaptcha/commit/4d5de26856b4dd890376e02bb40a3e5be2928bf4

**Comment by baigod** [comment]
Thank you very much. I'm running 👍 👍 👍
