### ISSUE TITLE
大神，这是什么问题Centos 6.8/6.9

### ISSUE THREAD

**Issue by baigod** [eryx/hcaptcha#2]
/opt/hcaptcha/bin/hcaptchad: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory

**Comment by baigod** [comment]
并且之前装的一台，centos7.3 ,怎么都验证不通过

**Comment by eryx** [comment]
@15174834 CentOS 6.x 系列 libevent　前后有 1.4.x 2.0.x 两个版本，编译时依赖 libevent-devel 或 libevent2-devel, 运行时依赖 libevent 或 libevent2, 你需要保持 编译和运行环境一致。

验证问题可能是: 
* 确认连接的 memcached 数据库可用性
* 基于安全考虑(暴力重试)，每次验证无论对错，该 word 都被清除，前端需要重新请求新的 word-image
